"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['pyqt6_sample.py']
DATA_FILES = []
OPTIONS = {}

setup(
    app=APP,
	name='PyQt6 GUI Sample',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
